# Generated by Django 4.1 on 2022-08-15 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal"),
                            ("PUBLIC", "Public"),
                            ("OFFICIAL", "Official"),
                        ],
                        default="PERSONAL",
                        max_length=10,
                    ),
                ),
                (
                    "rate",
                    models.CharField(
                        choices=[("IMPORTANT", "Important"), ("HAVE_TIME", "HaveTime")],
                        default="HAVE_TIME",
                        max_length=12,
                    ),
                ),
                ("memo", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
